### PR TITLE
Add schematron rule to check for persName in bibl and clean existing bibl/persName tags

### PR DESCRIPTION
**Pull request by rlskoeser**
This update adds a new schematron rule to check for `persName` directly within `bibl`, and updates all existing card tei files (41) that failed the check.

As I was checking the updates, I did notice that there was a name in `hemingway.tei.xml` that looked a little odd, something about a title "to" a person rather than "by", which made me wonder if the name should be outside of the `bibl`.  

It would be great if someone could review the xml changes I made to make sure they look reasonable and then merge into develop, that would be great.

### CODE REVIEW

**Comment by rlskoeser** [comment]
FWIW, I also added some documentation to the schematron page of the wiki with steps for adding new schematron rules:
https://github.com/Princeton-CDH/mapping-expatriate-paris/wiki/Validating-card-encoding-with-schematron#workflow-for-adding-new-schematron-rules

**Comment by elspethgreen** [comment]
The corrections look good!  Indeed, the Hemingway card had a weird mis-encoding that I corrected, as did the Church card.  I'm not sure what's causing the conflicts, though.

**Comment by rlskoeser** [comment]
@elspethgreen thanks for reviewing and making the fixes.  I'll try to take a look soon to see if can resolve the conflicts.

**Comment by rlskoeser** [comment]
@elspethgreen I updated the feature branch with the latest from develop and reconciled the changes.  It looked to me like it was a combination of whitespace changes and encoding being added.

Would you review the last set of changes and then merge the pull request once you're satisfied?

**Pull request merged**
