### PR TITLE
Automated data build

### PR DESCRIPTION
**Pull request by rlskoeser**
This isn't quite ready to merge yet, but I need some help figuring out how to fix the remaining schematron validation issues because I'm not familiar enough with the encoding conventions for borrowing events.  I don't need you to review the data build itself, but I think it would be a good idea to have someone look over the xml changes.

Here's a summary of the changes I've made so far that I think you should be aware of:

- generated XSD schemas from existing RNC schemas for logbooks and personography (the tool I'm using doesn't like the RNC schemas for some reason)
- I had to tweak the personography.xsd to work around a bug in libxml2; I think what I've done is equivalent, but I left the old version commented out with a note and a link to the bug in case we run into problems.
- I also had to make a small tweak the schematron `libcards.sch` in order to run it with the tools I'm using.  I followed the instructions in the wiki to run it in Oxygen and it doesn't seem like the change breaks anything, but it would be good to have someone more familiar with it double check.
- removed an xml include of the personography in logbook-1919 because it was causing a validation error (it isn't a problem in Oxygen, but fails with the libxml parser for some reason); this doesn't seem to be needed, and wasn't present in any of the other logbooks
- minor cleanup on a handful of card files to make them valid TEI.  Most of these were pretty straightforward and obvious.  The mcnair file had an empty `ana` attribute and no person name, but I see there is an issue related to this (#350); I commented out the empty `@ana` for now.

The schematron errors are visible in the travis-ci build output: https://travis-ci.org/Princeton-CDH/mapping-expatriate-paris/builds/193891871
Unfortunately, it is pretty verbose and doesn't provide line numbers, so it isn't super readable.  I think it will probably be easier to look at those files in Oxygen to investigate.    I'm willing to help clean these up if someone will provide information on what needs to be done.

Question: do you want me to add revision description entries for the minor xml cleanup I did to get the TEI validation to pass on the cards?

Separate note: `bonnerot.tei.xml` seems to have the wrong name in the title statement and heading (Marguerite Bloch instead of Louis Bonnerot); I noticed this when I was comparing other documents to clean up `bloch.tei.xml`.  Should I create a new issue to fix this?  Should we think about checking the documents more generally for other mismatch errors like this?

### CODE REVIEW

**Comment by jkotin** [comment]
Hi Rebecca --

Thank you for this email.  I have a lot of questions about the below -- some of which I don't yet fully understand.  Perhaps we could talk about the changes before implementing them?  Ellie can discuss the encoding conventions for the borrowing events with you.

Very best,

Josh

**Comment by elspethgreen** [comment]
I'm happy to provide a more thorough description of the borrowing event conventions (see below), but I'm not sure I understand many of the issues you've raised.  My questions:
1.  What are XSD and RNC schemas?  How were they originally implemented, and what exactly have you changed?
2.  What does the schematron libcards.sch do?  I see that it's a header on all of the cards, but I don't know its significance.  Is it Cliff's specialized terminology, in addition to normal TEI (like, what allows things to be tagged as a "borrowingEvent")?
EDIT:  I took a look at libcards, and it does not seem to be Cliff's specialized terminology.  Is this a generalized TEI schema?  

Here's an explanation of the borrowingEvent encoding process:
1.  Cliff ran a systematic search for items in this pattern:  date, bibl, date.  Since borrowing events tend to be arranged on the card in a rough grid, this search picks up most of them.
2.  The first date was auto-tagged with the attribute "checkedOut," the bibl with "borrowedItem" and a "corresp ID"--a unique identifier based on a set of regularized titles assembled in the file "borrowed-titles.xml" and the second date with "returned."
3.  The encoder receives the file in this state.
4.  The encoder, going bibl by bibl, checks (against the card image available from the diglib archive) that each "borrowedItem" is indeed a borrowed item, and that the dates tagged as "checkedOut" and "returned" indeed represent that information.
5.  If the book is not borrowed, or the dates have been incorrectly labeled, the encoder makes the appropriate corrections.  Regardless of whether a book is borrowed or not, the encoder always leaves the "corresp ID" intact.
6.  If the book is indeed borrowed, and once the date tagging is correct, the encoder encases the set of "date, bibl, date" within an <ab> tag with the attribute "#borrowingEvent"
8.  If a book was borrowed and THEN bought, encoders put the book within the <ab> for a borrowingEvent.  Rather than the second date, they include the note from the card that indicates the book was bought ("BB" or "bought book" or some variation on that).
9.  If the book was bought straightaway, or merely mentioned, or otherwise NOT part of a borrowingEvent, no #borrowingEvent <ab> tag is added.
7.  All other stray text outside of the <head> tag is encased in <note> tags.  If the note is regarding a specific book, the note goes within borrowingEvent <ab> tags.

**Comment by rlskoeser** [comment]
Thanks for the feedback.  Responses to your questions:

1. XSD and RNC are two different formats of XML schemas.  Cliff originally created the schemas in the RNC format, but I don't know on what basis - I assume using a subset of the full TEI schema, perhaps customized based on the tags he expected to use.  I converted the RNC to XSD using OxygenXML, but had to tweak one of them due to a bug in one of the xml libraries I'm working with.  (It would probably be a good idea to have schema review on the list of work we want from our XML consultant.)
2. Schematron is a specialized validation tool that lets you check things at a more granular level than an XML schema (which really only checks for things like required elements, order, and data format in some cases, like for regularized dates).    

The `libcards.sch` that Cliff wrote currently includes 4 checks:
- `tei:date` elements in `tei:note` should not have an `@ana` of `#checkedOut` or `#returned`
- a borrowing event should have exactly one borrowed item
- a borrowing event should not have more than one checked out date
- a borrowing event should not have more than one return date

We can revise those rules if necessary, and we can certainly add new ones, depending on what you all come up with that you think could be validated automatically.

Based on your comments, I wonder if some of the dates within notes that are failing the first schematron check were ones that were auto-tagged.

**Comment by elspethgreen** [comment]
Yes, dates with "checkedOut" and "returned" attributes outside of "borrowingEvents" are almost certainly the result of the auto-tagging.  Encoders are supposed to remove these attributes when they find them, but I'm sure, inevitably, they've missed some.

**Comment by elspethgreen** [comment]
Okay--I'm working in the feature/data-build branch now, and my corrections to "lamy" resulted in that card being taken off the list of failing cards from the first Travis Cl build

**Comment by elspethgreen** [comment]
Can the Travis Cl build return the line numbers of the errors?  The Raphael still has 5 instances of extra borrowedItem tags, and it's a needle in a haystack to find them (not to mention the nightmare of the Killen and Kittredge cards)

**Comment by bwhicks** [comment]
@elspethgreen : Pending tweaks to the travis-ci, for Raphael:

826:<ab ana="#borrowingEvent"><date ana="#checkedOut" when="1930-09-24"> 24 </date> <bibl ana="#borrowedItem" corresp="mep:008m82"><title>Table Talk,</title></bibl> <bibl ana="#borrowedItem"><author>Hazlitt</author></bibl> <date ana="#returned" when="1930-10-02">Oct. 2nd.</date></ab>
1076:<ab ana="#borrowingEvent"><date ana="#checkedOut" when="1934-03-11">11 March</date> <bibl ana="#borrowedItem" corresp="mep:003p2j"><title>Backstreet</title></bibl> <bibl ana="#borrowedItem"><author>Danton</author></bibl> 73.39 <date ana="#returned" when="1934-03-15">15 Mar.</date></ab>
1127:<ab ana="#borrowingEvent"><date ana="#checkedOut" when="1934-12-07">Dec 7</date> <bibl ana="#borrowedItem" corresp="mep:002r1j"><title>Wells Autobiog </title></bibl><bibl ana="#borrowedItem"><biblScope>vol II</biblScope></bibl> <date ana="#returned" when="1934-12-14">Dec 14</date></ab>
1149:<ab ana="#borrowingEvent"><date ana="#checkedOut" when="1935-03-09">9 -</date> <bibl ana="#borrowedItem" corresp="mep:00vk21"><title>Proud </title></bibl> <bibl ana="#borrowedItem"><author>(Irwin)</author></bibl> <date ana="#returned" when="1935-03-15">15</date></ab>
1308:<ab ana="#borrowingEvent"><date ana="#checkedOut" when="1937-02-13"> 13 </date> <bibl ana="#borrowedItem" corresp="mep:005x66"><title>Letters of Gertrude Bell</title></bibl> <bibl ana="#borrowedItem"><biblScope>Vol II.</biblScope></bibl><date ana="#returned" when="1937-02-20"> Feb 20</date></ab>

I did this from the Mac terminal by:
`cd /Users/Benjamin/mapping-expatriate-paris/transcriptions/cards/r` (where I happened to have cloned the repo)
`grep -n 'borrowedItem.*borrowedItem' raphael.tei.xml` (searches the file for any lines with borrowedItem at least twice, and the `-n` returns a line number)

Not a substitute for validation, but handy in a pinch.

**Comment by rlskoeser** [comment]
I don't know why the travis-ci build isn't returning line numbers - I can try to look into this at some point, but I think a fairly easy workaround/solution would be to add the libcards.sch processing instruction in Oxygen - if you do that, it should give you a red highlight where there are errors.

**Comment by elspethgreen** [comment]
SUCCESS!!!!!

**Comment by rlskoeser** [comment]
@elspethgreen awesome! very nice work.  The build is passing - I just had a small glitch in my code that was sending the wrong exit code, which made travis think there was an error even though there wasn't one.   (Sorry!)

I checked it on my local copy as well - everything is passing now!

**Comment by rlskoeser** [comment]
@elspethgreen if you've had the chance to look over the other xml changes I made along the way (minor tei cleanup, etc) and are comfortable with it - I _think_ we can go ahead and merge this into develop now, and start using it!

**Comment by elspethgreen** [comment]
Merge away!

**Pull request merged**
