### PR TITLE
stirling dates added and borrowing events taken out

### PR DESCRIPTION
**Pull request by clmahoney**
S7 is an account note that fits with the dates of the previous card.

### CODE REVIEW

**Comment by elspethgreen** [comment]
Hey Cate--would you mind notBefore/notAfter-ing these 1900 dates?  Even if it's the full range of the library!

**Comment by clmahoney** [comment]
Yes will do!

**Comment by elspethgreen** [comment]
Hi Ben--I'm not sure how to resolve the conflicts in this merge.  It seems to be a matter of dates not matching up (the correct year is 1941!), but don't know why it happened!

**Comment by elspethgreen** [comment]
Rebecca--do you know what's going on with these conflicts?

**Comment by rlskoeser** [comment]
@elspethgreen If you click on the 'resolve conflicts' button you'll see the web editor that highlights the conflicting lines of xml.  It looks like a difference in the not after dates - one version has 1940 and the other has 1941.  Once you select which edit you want to keep you'll be able to merge the pull request.

**Pull request closed without merging**
